import type { Metadata } from "next";
import { appTheme, ThemeType } from "@/util/appTheme";
import appDetails from "../util/appDetails.json"
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Next Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: appTheme[appDetails.default_theme as ThemeType].background_1 }}>
      <body>
        {children}
      </body>
    </html>
  );
}
